apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "questops.fullname" . }}-config
  labels:
    {{- include "questops.labels" . | nindent 4 }}
data:
  DEMO_MODE: {{ .Values.app.demoMode | quote }}
  OLLAMA_URL: {{ .Values.ai.ollamaUrl | quote }}
  OLLAMA_MODEL: {{ .Values.ai.ollamaModel | quote }}
  JIRA_BASE_URL: {{ .Values.jira.baseUrl | quote }}
  JIRA_PROJECT_KEY: {{ .Values.jira.projectKey | quote }}
  JIRA_USER: {{ .Values.jira.user | quote }}
  JIRA_BOARD_STATUSES: {{ .Values.jira.boardStatuses | quote }}
  JIRA_DONE_STATUSES: {{ .Values.jira.doneStatuses | quote }}
  JIRA_REVIEW_STATUSES: {{ .Values.jira.reviewStatuses | quote }}
  JIRA_REOPENED_STATUSES: {{ .Values.jira.reopenedStatuses | quote }}
  JENKINS_URL: {{ .Values.jenkins.url | quote }}
  JENKINS_USER: {{ .Values.jenkins.user | quote }}
  JENKINS_LONG_RUNNING_FACTOR: {{ .Values.jenkins.longRunningFactor | quote }}
  JENKINS_LONG_RUNNING_MINUTES: {{ .Values.jenkins.longRunningMinutes | quote }}
  JENKINS_FAILURE_WINDOW_DAYS: {{ .Values.jenkins.failureWindowDays | quote }}
  JENKINS_IGNORE: {{ .Values.jenkins.ignore | quote }}
  JIRA_CLOSED_WINDOW_DAYS: {{ .Values.jira.closedWindowDays | quote }}
  ES_URL: {{ .Values.elasticsearch.url | quote }}
  ES_VERIFY_SSL: {{ .Values.elasticsearch.verifySsl | quote }}
  JENKINS_KPI_INDEX: {{ .Values.elasticsearch.kpiIndex | quote }}
  ERROR_ANALYSIS_INDEX: {{ .Values.elasticsearch.errorAnalysisIndex | quote }}
  KPI_SYNC_MINUTES: {{ .Values.elasticsearch.kpiSyncMinutes | quote }}
  KPI_MAX_DOCS: {{ .Values.elasticsearch.kpiMaxDocs | quote }}
  KPI_IGNORE: {{ .Values.elasticsearch.kpiIgnore | quote }}
  UPGRADES_PROXY: {{ .Values.upgrades.proxy | quote }}
  UPGRADES_VERIFY_SSL: {{ .Values.upgrades.verifySsl | quote }}
  EOL_API_BASE: {{ .Values.upgrades.eolApiBase | quote }}
  GITHUB_API_BASE: {{ .Values.upgrades.githubApiBase | quote }}
  ERROR_ANALYSIS_DAYS: {{ .Values.elasticsearch.errorAnalysisDays | quote }}
  TZ: {{ .Values.app_timezone | quote }}
  LDAP_URL: {{ .Values.ldap.url | quote }}
  LDAP_BIND_DN: {{ .Values.ldap.bindDn | quote }}
  LDAP_BASE_DN: {{ .Values.ldap.baseDn | quote }}
  LDAP_USER_ATTR: {{ .Values.ldap.userAttr | quote }}
  LDAP_REQUIRED_GROUP: {{ .Values.ldap.requiredGroup | quote }}
  MEMBER_USERNAMES: {{ .Values.ldap.memberUsernames | quote }}
  GIT_USER_NAME: {{ .Values.git.userName | quote }}
  GIT_USER_EMAIL: {{ .Values.git.userEmail | quote }}
  REPOS_WORKDIR: {{ .Values.repositories.workdir | quote }}
  ADO_URL: {{ .Values.ado.url | quote }}
  ADO_USER: {{ .Values.ado.user | quote }}
  ADO_ACCESS_EXCLUDE: {{ .Values.ado.accessExclude | quote }}
