{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "questops.secretName" . }}
  labels:
    {{- include "questops.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.app.secretKey | quote }}
  DATABASE_URL: {{ include "questops.databaseUrl" . | quote }}
  JIRA_PASSWORD: {{ .Values.jira.password | quote }}
  JENKINS_TOKEN: {{ .Values.jenkins.token | quote }}
  ES_API_KEY: {{ .Values.elasticsearch.apiKey | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  GIT_TOKEN: {{ .Values.git.token | quote }}
  {{- range $i, $r := .Values.repositories.items }}
  REPO{{ add $i 1 }}_PASSWORD: {{ $r.password | default "" | quote }}
  {{- end }}
{{- end }}
