{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "questops.secretName" . }}
  labels:
    {{- include "questops.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.app.secretKey | quote }}
  DATABASE_URL: {{ include "questops.databaseUrl" . | quote }}
  JIRA_PAT: {{ .Values.jira.pat | quote }}
  JENKINS_TOKEN: {{ .Values.jenkins.token | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  GIT_TOKEN: {{ .Values.git.token | quote }}
{{- end }}
