apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meridian.fullname" . }}-env
  labels: {{- include "meridian.labels" . | nindent 4 }}
data:
  RUNNING_IN_CONTAINER: "true"
  FRONTEND_DIST: "/srv/static"
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
